import { getAssetPath } from './assetPath';

// ---------- Animals (60+ common animals) ----------
export const animals = [
  { id: 'cow', name: 'Cow', emoji: '🐮', sound: 'cow', color: 'bg-amber-600' },
  { id: 'dog', name: 'Dog', emoji: '🐶', sound: 'dog', color: 'bg-orange-400' },
  { id: 'cat', name: 'Cat', emoji: '🐱', sound: 'cat', color: 'bg-gray-400' },
  { id: 'sheep', name: 'Sheep', emoji: '🐑', sound: 'sheep', color: 'bg-white' },
  { id: 'duck', name: 'Duck', emoji: '🦆', sound: 'duck', color: 'bg-yellow-400' },
  { id: 'horse', name: 'Horse', emoji: '🐴', color: 'bg-brown-400' },
  { id: 'pig', name: 'Pig', emoji: '🐷', color: 'bg-pink-400' },
  { id: 'chicken', name: 'Chicken', emoji: '🐔', color: 'bg-yellow-300' },
  { id: 'goat', name: 'Goat', emoji: '🐐', color: 'bg-gray-300' },
  { id: 'turkey', name: 'Turkey', emoji: '🦃', color: 'bg-brown-300' },
  { id: 'rabbit', name: 'Rabbit', emoji: '🐇', color: 'bg-white' },
  { id: 'frog', name: 'Frog', emoji: '🐸', color: 'bg-green-400' },
  { id: 'turtle', name: 'Turtle', emoji: '🐢', color: 'bg-green-600' },
  { id: 'snake', name: 'Snake', emoji: '🐍', color: 'bg-green-500' },
  { id: 'lizard', name: 'Lizard', emoji: '🦎', color: 'bg-lime-500' },
  { id: 'monkey', name: 'Monkey', emoji: '🐒', color: 'bg-brown-500' },
  { id: 'gorilla', name: 'Gorilla', emoji: '🦍', color: 'bg-gray-700' },
  { id: 'elephant', name: 'Elephant', emoji: '🐘', color: 'bg-gray-500' },
  { id: 'lion', name: 'Lion', emoji: '🦁', color: 'bg-yellow-600' },
  { id: 'tiger', name: 'Tiger', emoji: '🐯', color: 'bg-orange-600' },
  { id: 'leopard', name: 'Leopard', emoji: '🐆', color: 'bg-yellow-700' },
  { id: 'zebra', name: 'Zebra', emoji: '🦓', color: 'bg-white' },
  { id: 'giraffe', name: 'Giraffe', emoji: '🦒', color: 'bg-yellow-400' },
  { id: 'rhino', name: 'Rhinoceros', emoji: '🦏', color: 'bg-gray-500' },
  { id: 'hippo', name: 'Hippopotamus', emoji: '🦛', color: 'bg-purple-400' },
  { id: 'camel', name: 'Camel', emoji: '🐫', color: 'bg-yellow-600' },
  { id: 'llama', name: 'Llama', emoji: '🦙', color: 'bg-white' },
  { id: 'kangaroo', name: 'Kangaroo', emoji: '🦘', color: 'bg-orange-500' },
  { id: 'koala', name: 'Koala', emoji: '🐨', color: 'bg-gray-400' },
  { id: 'panda', name: 'Panda', emoji: '🐼', color: 'bg-white' },
  { id: 'bear', name: 'Bear', emoji: '🐻', color: 'bg-brown-600' },
  { id: 'fox', name: 'Fox', emoji: '🦊', color: 'bg-orange-400' },
  { id: 'wolf', name: 'Wolf', emoji: '🐺', color: 'bg-gray-500' },
  { id: 'deer', name: 'Deer', emoji: '🦌', color: 'bg-brown-400' },
  { id: 'moose', name: 'Moose', emoji: '🦌', color: 'bg-brown-600' },
  { id: 'raccoon', name: 'Raccoon', emoji: '🦝', color: 'bg-gray-400' },
  { id: 'skunk', name: 'Skunk', emoji: '🦨', color: 'bg-black' },
  { id: 'otter', name: 'Otter', emoji: '🦦', color: 'bg-brown-300' },
  { id: 'beaver', name: 'Beaver', emoji: '🦫', color: 'bg-brown-500' },
  { id: 'hedgehog', name: 'Hedgehog', emoji: '🦔', color: 'bg-brown-400' },
  { id: 'porcupine', name: 'Porcupine', emoji: '🦔', color: 'bg-brown-500' },
  { id: 'bat', name: 'Bat', emoji: '🦇', color: 'bg-gray-700' },
  { id: 'owl', name: 'Owl', emoji: '🦉', color: 'bg-brown-400' },
  { id: 'eagle', name: 'Eagle', emoji: '🦅', color: 'bg-yellow-600' },
  { id: 'hawk', name: 'Hawk', emoji: '🦅', color: 'bg-brown-500' },
  { id: 'parrot', name: 'Parrot', emoji: '🦜', color: 'bg-green-400' },
  { id: 'penguin', name: 'Penguin', emoji: '🐧', color: 'bg-blue-400' },
  { id: 'seal', name: 'Seal', emoji: '🦭', color: 'bg-gray-400' },
  { id: 'dolphin', name: 'Dolphin', emoji: '🐬', color: 'bg-blue-400' },
  { id: 'whale', name: 'Whale', emoji: '🐋', color: 'bg-blue-500' },
  { id: 'shark', name: 'Shark', emoji: '🦈', color: 'bg-blue-400' },
  { id: 'octopus', name: 'Octopus', emoji: '🐙', color: 'bg-purple-400' },
  { id: 'crab', name: 'Crab', emoji: '🦀', color: 'bg-red-400' },
  { id: 'lobster', name: 'Lobster', emoji: '🦞', color: 'bg-red-500' },
  { id: 'shrimp', name: 'Shrimp', emoji: '🦐', color: 'bg-pink-300' },
  { id: 'snail', name: 'Snail', emoji: '🐌', color: 'bg-brown-400' },
  { id: 'butterfly', name: 'Butterfly', emoji: '🦋', color: 'bg-purple-300' },
  { id: 'bee', name: 'Bee', emoji: '🐝', color: 'bg-yellow-400' },
  { id: 'ant', name: 'Ant', emoji: '🐜', color: 'bg-black' },
  { id: 'ladybug', name: 'Ladybug', emoji: '🐞', color: 'bg-red-500' },
  { id: 'spider', name: 'Spider', emoji: '🕷️', color: 'bg-gray-600' },
];

// ---------- Shapes (20+ including 3D) ----------
export const shapes = [
  { id: 'circle', name: 'Circle', emoji: '⬤', color: 'bg-red-400' },
  { id: 'square', name: 'Square', emoji: '■', color: 'bg-blue-400' },
  { id: 'triangle', name: 'Triangle', emoji: '▲', color: 'bg-green-400' },
  { id: 'rectangle', name: 'Rectangle', emoji: '▬', color: 'bg-yellow-400' },
  { id: 'star', name: 'Star', emoji: '★', color: 'bg-purple-400' },
  { id: 'heart', name: 'Heart', emoji: '♥', color: 'bg-pink-400' },
  { id: 'oval', name: 'Oval', emoji: '⬭', color: 'bg-indigo-400' },
  { id: 'diamond', name: 'Diamond', emoji: '♦', color: 'bg-orange-400' },
  { id: 'crescent', name: 'Crescent', emoji: '☾', color: 'bg-teal-400' },
  { id: 'cross', name: 'Cross', emoji: '✚', color: 'bg-cyan-400' },
  { id: 'pentagon', name: 'Pentagon', emoji: '⬟', color: 'bg-lime-400' },
  { id: 'hexagon', name: 'Hexagon', emoji: '⬡', color: 'bg-amber-400' },
  { id: 'octagon', name: 'Octagon', emoji: '⯐', color: 'bg-emerald-400' },
  { id: 'trapezoid', name: 'Trapezoid', emoji: '⏢', color: 'bg-violet-400' },
  { id: 'parallelogram', name: 'Parallelogram', emoji: '▱', color: 'bg-fuchsia-400' },
  { id: 'semicircle', name: 'Semicircle', emoji: '◠', color: 'bg-rose-400' },
  { id: 'cube', name: 'Cube', emoji: '🧊', color: 'bg-blue-300' },
  { id: 'sphere', name: 'Sphere', emoji: '⚪', color: 'bg-gray-300' },
  { id: 'cylinder', name: 'Cylinder', emoji: '🥫', color: 'bg-yellow-300' },
  { id: 'cone', name: 'Cone', emoji: '🎩', color: 'bg-purple-300' },
  { id: 'pyramid', name: 'Pyramid', emoji: '🔺', color: 'bg-orange-300' },
];

// ---------- Counting Objects (100+ already) ----------
export const countingObjects = [
  { emoji: '🍎', name: 'apples' },
  { emoji: '🍌', name: 'bananas' },
  { emoji: '🍊', name: 'oranges' },
  { emoji: '🍇', name: 'grapes' },
  { emoji: '🍓', name: 'strawberries' },
  { emoji: '🍒', name: 'cherries' },
  { emoji: '🥝', name: 'kiwis' },
  { emoji: '🍍', name: 'pineapples' },
  { emoji: '🥭', name: 'mangoes' },
  { emoji: '🍉', name: 'watermelons' },
  { emoji: '🥥', name: 'coconuts' },
  { emoji: '🍋', name: 'lemons' },
  { emoji: '🍈', name: 'melons' },
  { emoji: '🫐', name: 'blueberries' },
  { emoji: '🍑', name: 'peaches' },
  { emoji: '🍐', name: 'pears' },
  { emoji: '🥑', name: 'avocados' },
  { emoji: '🥕', name: 'carrots' },
  { emoji: '🥦', name: 'broccoli' },
  { emoji: '🍅', name: 'tomatoes' },
  { emoji: '🫑', name: 'peppers' },
  { emoji: '🥒', name: 'cucumbers' },
  { emoji: '🥬', name: 'lettuce' },
  { emoji: '🧅', name: 'onions' },
  { emoji: '🧄', name: 'garlic' },
  { emoji: '🫘', name: 'beans' },
  { emoji: '🥔', name: 'potatoes' },
  { emoji: '🍠', name: 'sweet potatoes' },
  { emoji: '🌽', name: 'corn' },
  { emoji: '🥜', name: 'peanuts' },
  { emoji: '🥚', name: 'eggs' },
  { emoji: '🥛', name: 'milk bottles' },
  { emoji: '🧀', name: 'cheese slices' },
  { emoji: '🥩', name: 'steaks' },
  { emoji: '🥓', name: 'bacon strips' },
  { emoji: '🍗', name: 'chicken legs' },
  { emoji: '🍔', name: 'hamburgers' },
  { emoji: '🍕', name: 'pizza slices' },
  { emoji: '🌭', name: 'hot dogs' },
  { emoji: '🥪', name: 'sandwiches' },
  { emoji: '🍦', name: 'ice cream cones' },
  { emoji: '🍩', name: 'donuts' },
  { emoji: '🍪', name: 'cookies' },
  { emoji: '🎂', name: 'cakes' },
  { emoji: '🍫', name: 'chocolate bars' },
  { emoji: '🍬', name: 'candies' },
  { emoji: '🍭', name: 'lollipops' },
  { emoji: '🍯', name: 'honey pots' },
  { emoji: '🥨', name: 'pretzels' },
  { emoji: '🥖', name: 'baguettes' },
  { emoji: '🥐', name: 'croissants' },
  { emoji: '🥞', name: 'pancakes' },
  { emoji: '🧇', name: 'waffles' },
  { emoji: '🍳', name: 'fried eggs' },
  { emoji: '🧈', name: 'butter pads' },
  { emoji: '🥫', name: 'canned food' },
  { emoji: '🍱', name: 'bento boxes' },
  { emoji: '🍘', name: 'rice crackers' },
  { emoji: '🍙', name: 'rice balls' },
  { emoji: '🍚', name: 'rice bowls' },
  { emoji: '🍛', name: 'curry rice' },
  { emoji: '🍜', name: 'ramen noodles' },
  { emoji: '🍝', name: 'spaghetti' },
  { emoji: '🍢', name: 'oden skewers' },
  { emoji: '🍣', name: 'sushi rolls' },
  { emoji: '🍤', name: 'fried shrimp' },
  { emoji: '🍥', name: 'fish cakes' },
  { emoji: '🥮', name: 'mooncakes' },
  { emoji: '🍡', name: 'dango dumplings' },
  { emoji: '🥟', name: 'dumplings' },
  { emoji: '🥠', name: 'fortune cookies' },
  { emoji: '🥡', name: 'takeout boxes' },
  { emoji: '🦀', name: 'crabs' },
  { emoji: '🦞', name: 'lobsters' },
  { emoji: '🦐', name: 'shrimps' },
  { emoji: '🦑', name: 'squids' },
  { emoji: '🐙', name: 'octopuses' },
  { emoji: '🐟', name: 'fish' },
  { emoji: '🐠', name: 'tropical fish' },
  { emoji: '🐡', name: 'blowfish' },
  { emoji: '🐬', name: 'dolphins' },
  { emoji: '🐳', name: 'whales' },
  { emoji: '🐋', name: 'whales' },
  { emoji: '🦈', name: 'sharks' },
  { emoji: '🐊', name: 'crocodiles' },
  { emoji: '🐢', name: 'turtles' },
  { emoji: '🦎', name: 'lizards' },
  { emoji: '🐍', name: 'snakes' },
  { emoji: '🐦', name: 'birds' },
  { emoji: '🐧', name: 'penguins' },
  { emoji: '🕊️', name: 'doves' },
  { emoji: '🦅', name: 'eagles' },
  { emoji: '🦆', name: 'ducks' },
  { emoji: '🦢', name: 'swans' },
  { emoji: '🦉', name: 'owls' },
  { emoji: '🦩', name: 'flamingos' },
  { emoji: '🐓', name: 'roosters' },
  { emoji: '🦃', name: 'turkeys' },
  { emoji: '🐕', name: 'dogs' },
  { emoji: '🐩', name: 'poodles' },
  { emoji: '🐈', name: 'cats' },
  { emoji: '🐈‍⬛', name: 'black cats' },
  { emoji: '🐇', name: 'rabbits' },
  { emoji: '🐁', name: 'mice' },
  { emoji: '🐀', name: 'rats' },
  { emoji: '🐹', name: 'hamsters' },
  { emoji: '🐿️', name: 'chipmunks' },
  { emoji: '🦔', name: 'hedgehogs' },
  { emoji: '🦇', name: 'bats' },
  { emoji: '🐻', name: 'bears' },
  { emoji: '🐼', name: 'pandas' },
  { emoji: '🐨', name: 'koalas' },
  { emoji: '🐯', name: 'tigers' },
  { emoji: '🦁', name: 'lions' },
  { emoji: '🐮', name: 'cows' },
  { emoji: '🐷', name: 'pigs' },
  { emoji: '🐸', name: 'frogs' },
  { emoji: '🐒', name: 'monkeys' },
  { emoji: '🦍', name: 'gorillas' },
  { emoji: '🦧', name: 'orangutans' },
  { emoji: '🐴', name: 'horses' },
  { emoji: '🦄', name: 'unicorns' },
  { emoji: '🦓', name: 'zebras' },
  { emoji: '🦌', name: 'deer' },
  { emoji: '🦬', name: 'bisons' },
  { emoji: '🐃', name: 'buffaloes' },
  { emoji: '🐂', name: 'oxen' },
  { emoji: '🐐', name: 'goats' },
  { emoji: '🐏', name: 'rams' },
  { emoji: '🐑', name: 'sheep' },
  { emoji: '🐫', name: 'camels' },
  { emoji: '🦙', name: 'llamas' },
  { emoji: '🦒', name: 'giraffes' },
  { emoji: '🐘', name: 'elephants' },
  { emoji: '🦏', name: 'rhinos' },
  { emoji: '🦛', name: 'hippos' },
  { emoji: '🐪', name: 'camels' },
  { emoji: '🦘', name: 'kangaroos' },
  { emoji: '🦡', name: 'badgers' },
  { emoji: '🦨', name: 'skunks' },
  { emoji: '🦦', name: 'otters' },
  { emoji: '🦥', name: 'sloths' },
  { emoji: '🐾', name: 'paw prints' },
  { emoji: '🪶', name: 'feathers' },
  { emoji: '🪰', name: 'flies' },
  { emoji: '🪲', name: 'beetles' },
  { emoji: '🐞', name: 'ladybugs' },
  { emoji: '🦗', name: 'crickets' },
  { emoji: '🕷️', name: 'spiders' },
  { emoji: '🦂', name: 'scorpions' },
  { emoji: '🐜', name: 'ants' },
  { emoji: '🐝', name: 'bees' },
  { emoji: '🪱', name: 'worms' },
  { emoji: '🐌', name: 'snails' },
  { emoji: '🦋', name: 'butterflies' },
  { emoji: '🐛', name: 'caterpillars' },
  { emoji: '🪳', name: 'cockroaches' },
  { emoji: '🌻', name: 'sunflowers' },
  { emoji: '🌼', name: 'daisies' },
  { emoji: '🌸', name: 'cherry blossoms' },
  { emoji: '🌺', name: 'hibiscus' },
  { emoji: '🌷', name: 'tulips' },
  { emoji: '🌹', name: 'roses' },
  { emoji: '🌿', name: 'herbs' },
  { emoji: '🍀', name: 'four-leaf clovers' },
  { emoji: '🌱', name: 'seedlings' },
  { emoji: '🌲', name: 'trees' },
  { emoji: '🌳', name: 'trees' },
  { emoji: '🌴', name: 'palm trees' },
  { emoji: '🌵', name: 'cacti' },
  { emoji: '☀️', name: 'suns' },
  { emoji: '⭐', name: 'stars' },
  { emoji: '🌙', name: 'moons' },
  { emoji: '☁️', name: 'clouds' },
  { emoji: '🌈', name: 'rainbows' },
  { emoji: '⚡', name: 'lightnings' },
  { emoji: '❄️', name: 'snowflakes' },
  { emoji: '🔥', name: 'fires' },
  { emoji: '💧', name: 'water drops' },
  { emoji: '🌊', name: 'waves' },
  { emoji: '⛰️', name: 'mountains' },
  { emoji: '🏔️', name: 'mountains' },
  { emoji: '🗻', name: 'mount fuji' },
  { emoji: '🏝️', name: 'islands' },
  { emoji: '🏖️', name: 'beaches' },
  { emoji: '🏜️', name: 'deserts' },
  { emoji: '🏞️', name: 'national parks' },
  { emoji: '🌋', name: 'volcanoes' },
  { emoji: '⛲', name: 'fountains' },
  { emoji: '⛺', name: 'tents' },
  { emoji: '🏠', name: 'houses' },
  { emoji: '🏡', name: 'houses' },
  { emoji: '🏢', name: 'buildings' },
  { emoji: '🏤', name: 'post offices' },
  { emoji: '🏥', name: 'hospitals' },
  { emoji: '🏦', name: 'banks' },
  { emoji: '🏨', name: 'hotels' },
  { emoji: '🏩', name: 'love hotels' },
  { emoji: '🏪', name: 'convenience stores' },
  { emoji: '🏫', name: 'schools' },
  { emoji: '🏬', name: 'department stores' },
  { emoji: '🏭', name: 'factories' },
  { emoji: '🏯', name: 'castles' },
  { emoji: '🏰', name: 'castles' },
  { emoji: '💒', name: 'weddings' },
  { emoji: '🗼', name: 'towers' },
  { emoji: '🗽', name: 'statues' },
  { emoji: '⛪', name: 'churches' },
  { emoji: '🕌', name: 'mosques' },
  { emoji: '🛕', name: 'temples' },
  { emoji: '🕍', name: 'synagogues' },
  { emoji: '⛩️', name: 'shrines' },
  { emoji: '🎠', name: 'carousels' },
  { emoji: '🎡', name: 'ferris wheels' },
  { emoji: '🎢', name: 'roller coasters' },
  { emoji: '🎪', name: 'circus tents' },
  { emoji: '🎨', name: 'paint palettes' },
  { emoji: '🎭', name: 'drama masks' },
  { emoji: '🎬', name: 'clapperboards' },
  { emoji: '🎤', name: 'microphones' },
  { emoji: '🎧', name: 'headphones' },
  { emoji: '🎷', name: 'saxophones' },
  { emoji: '🎸', name: 'guitars' },
  { emoji: '🎹', name: 'pianos' },
  { emoji: '🎺', name: 'trumpets' },
  { emoji: '🎻', name: 'violins' },
  { emoji: '🥁', name: 'drums' },
  { emoji: '🎲', name: 'dice' },
  { emoji: '♟️', name: 'chess pawns' },
  { emoji: '🎯', name: 'dart boards' },
  { emoji: '🎳', name: 'bowling balls' },
  { emoji: '🎮', name: 'video game controllers' },
  { emoji: '🎰', name: 'slot machines' },
  { emoji: '🧩', name: 'puzzle pieces' },
  { emoji: '🏀', name: 'basketballs' },
  { emoji: '🏈', name: 'footballs' },
  { emoji: '⚽', name: 'soccer balls' },
  { emoji: '⚾', name: 'baseballs' },
  { emoji: '🎾', name: 'tennis balls' },
  { emoji: '🏐', name: 'volleyballs' },
  { emoji: '🏉', name: 'rugby balls' },
  { emoji: '🥎', name: 'softballs' },
  { emoji: '🎱', name: 'pool balls' },
  { emoji: '🥏', name: 'frisbees' },
  { emoji: '🎣', name: 'fishing poles' },
  { emoji: '🥊', name: 'boxing gloves' },
  { emoji: '🥋', name: 'martial arts belts' },
  { emoji: '🚗', name: 'cars' },
  { emoji: '🚕', name: 'taxis' },
  { emoji: '🚙', name: 'SUVs' },
  { emoji: '🚌', name: 'buses' },
  { emoji: '🚎', name: 'trolleys' },
  { emoji: '🏎️', name: 'race cars' },
  { emoji: '🚓', name: 'police cars' },
  { emoji: '🚑', name: 'ambulances' },
  { emoji: '🚒', name: 'fire engines' },
  { emoji: '🚐', name: 'vans' },
  { emoji: '🚚', name: 'trucks' },
  { emoji: '🚛', name: 'lorries' },
  { emoji: '🚜', name: 'tractors' },
  { emoji: '🛺', name: 'rickshaws' },
  { emoji: '🚲', name: 'bicycles' },
  { emoji: '🛵', name: 'scooters' },
  { emoji: '🏍️', name: 'motorcycles' },
  { emoji: '🚨', name: 'police lights' },
  { emoji: '🚔', name: 'police cars' },
  { emoji: '🚍', name: 'buses' },
  { emoji: '🚘', name: 'cars' },
  { emoji: '🚖', name: 'taxis' },
  { emoji: '🚡', name: 'cable cars' },
  { emoji: '🚠', name: 'mountain railways' },
  { emoji: '🚟', name: 'suspension railways' },
  { emoji: '🚃', name: 'trains' },
  { emoji: '🚋', name: 'trams' },
  { emoji: '🚞', name: 'mountain trains' },
  { emoji: '🚝', name: 'monorails' },
  { emoji: '🚄', name: 'bullet trains' },
  { emoji: '🚅', name: 'bullet trains' },
  { emoji: '🚈', name: 'light rails' },
  { emoji: '🚂', name: 'locomotives' },
  { emoji: '🚀', name: 'rockets' },
  { emoji: '🛸', name: 'UFOs' },
  { emoji: '🚁', name: 'helicopters' },
  { emoji: '🛩️', name: 'small planes' },
  { emoji: '✈️', name: 'airplanes' },
  { emoji: '🛫', name: 'taking off' },
  { emoji: '🛬', name: 'landing' },
  { emoji: '⛵', name: 'sailboats' },
  { emoji: '🛥️', name: 'motorboats' },
  { emoji: '🚢', name: 'ships' },
  { emoji: '🛳️', name: 'cruise ships' },
  { emoji: '⚓', name: 'anchors' },
  { emoji: '🪐', name: 'planets' },
  { emoji: '🌍', name: 'earth' },
  { emoji: '🌏', name: 'earth' },
  { emoji: '🌎', name: 'earth' },
  { emoji: '🌕', name: 'full moons' },
  { emoji: '🌖', name: 'waning moons' },
  { emoji: '🌗', name: 'last quarters' },
  { emoji: '🌘', name: 'waning crescents' },
  { emoji: '🌑', name: 'new moons' },
  { emoji: '🌒', name: 'waxing crescents' },
  { emoji: '🌓', name: 'first quarters' },
  { emoji: '🌔', name: 'waxing moons' },
  { emoji: '💫', name: 'dizzy stars' },
  { emoji: '🌟', name: 'glowing stars' },
  { emoji: '🌠', name: 'shooting stars' },
  { emoji: '☄️', name: 'comets' },
];

// ---------- Emotions (12) ----------
export const emotions = [
  { id: 'happy', emoji: '😊', label: 'happy', bg: 'bg-yellow-200', color: 'text-yellow-800' },
  { id: 'sad', emoji: '😢', label: 'sad', bg: 'bg-blue-200', color: 'text-blue-800' },
  { id: 'angry', emoji: '😠', label: 'angry', bg: 'bg-red-200', color: 'text-red-800' },
  { id: 'surprised', emoji: '😲', label: 'surprised', bg: 'bg-purple-200', color: 'text-purple-800' },
  { id: 'scared', emoji: '😨', label: 'scared', bg: 'bg-gray-200', color: 'text-gray-800' },
  { id: 'silly', emoji: '😜', label: 'silly', bg: 'bg-green-200', color: 'text-green-800' },
  { id: 'excited', emoji: '🤩', label: 'excited', bg: 'bg-pink-200', color: 'text-pink-800' },
  { id: 'tired', emoji: '😴', label: 'tired', bg: 'bg-indigo-200', color: 'text-indigo-800' },
  { id: 'confused', emoji: '😕', label: 'confused', bg: 'bg-orange-200', color: 'text-orange-800' },
  { id: 'shy', emoji: '🥺', label: 'shy', bg: 'bg-red-100', color: 'text-red-600' },
  { id: 'proud', emoji: '😌', label: 'proud', bg: 'bg-teal-200', color: 'text-teal-800' },
  { id: 'lonely', emoji: '😔', label: 'lonely', bg: 'bg-gray-300', color: 'text-gray-800' },
];

// ---------- Sports Equipment (30+ emoji only) ----------
export const sportsEquipment = [
  { id: 'soccer', name: 'Soccer Ball', emoji: '⚽' },
  { id: 'basketball', name: 'Basketball', emoji: '🏀' },
  { id: 'football', name: 'Football', emoji: '🏈' },
  { id: 'baseball', name: 'Baseball', emoji: '⚾' },
  { id: 'tennis', name: 'Tennis Ball', emoji: '🎾' },
  { id: 'volleyball', name: 'Volleyball', emoji: '🏐' },
  { id: 'rugby', name: 'Rugby Ball', emoji: '🏉' },
  { id: 'bowling', name: 'Bowling Ball', emoji: '🎳' },
  { id: 'hockey', name: 'Hockey Stick', emoji: '🏒' },
  { id: 'fieldhockey', name: 'Field Hockey Stick', emoji: '🏑' },
  { id: 'lacrosse', name: 'Lacrosse Stick', emoji: '🥍' },
  { id: 'pingpong', name: 'Ping Pong Paddle', emoji: '🏓' },
  { id: 'badminton', name: 'Badminton Racket', emoji: '🏸' },
  { id: 'boxing', name: 'Boxing Gloves', emoji: '🥊' },
  { id: 'martialarts', name: 'Martial Arts Belt', emoji: '🥋' },
  { id: 'fencing', name: 'Fencing Sword', emoji: '🤺' },
  { id: 'golf', name: 'Golf Club', emoji: '⛳' },
  { id: 'skateboard', name: 'Skateboard', emoji: '🛹' },
  { id: 'rollerskate', name: 'Roller Skate', emoji: '🛼' },
  { id: 'ski', name: 'Ski', emoji: '⛷️' },
  { id: 'snowboard', name: 'Snowboard', emoji: '🏂' },
  { id: 'surfboard', name: 'Surfboard', emoji: '🏄' },
  { id: 'swim', name: 'Swim Goggles', emoji: '🥽' },
  { id: 'dumbbell', name: 'Dumbbell', emoji: '🏋️' },
  { id: 'frisbee', name: 'Frisbee', emoji: '🥏' },
  { id: 'kite', name: 'Kite', emoji: '🪁' },
  { id: 'parachute', name: 'Parachute', emoji: '🪂' },
  { id: 'binoculars', name: 'Binoculars', emoji: '🔭' },
  { id: 'compass', name: 'Compass', emoji: '🧭' },
  { id: 'stopwatch', name: 'Stopwatch', emoji: '⏱️' },
  { id: 'whistle', name: 'Whistle', emoji: '📢' },
];

// ---------- Musical Instruments (30+ emoji only) ----------
export const instruments = [
  { id: 'piano', name: 'Piano', emoji: '🎹' },
  { id: 'guitar', name: 'Guitar', emoji: '🎸' },
  { id: 'drums', name: 'Drums', emoji: '🥁' },
  { id: 'violin', name: 'Violin', emoji: '🎻' },
  { id: 'trumpet', name: 'Trumpet', emoji: '🎺' },
  { id: 'flute', name: 'Flute', emoji: '🎼' },
  { id: 'saxophone', name: 'Saxophone', emoji: '🎷' },
  { id: 'clarinet', name: 'Clarinet', emoji: '🎶' },
  { id: 'harp', name: 'Harp', emoji: '🪕' },
  { id: 'accordion', name: 'Accordion', emoji: '🪗' },
  { id: 'cello', name: 'Cello', emoji: '🎻' },
  { id: 'doublebass', name: 'Double Bass', emoji: '🎻' },
  { id: 'ukulele', name: 'Ukulele', emoji: '🎸' },
  { id: 'mandolin', name: 'Mandolin', emoji: '🎸' },
  { id: 'banjo', name: 'Banjo', emoji: '🪕' },
  { id: 'trombone', name: 'Trombone', emoji: '🎺' },
  { id: 'frenchhorn', name: 'French Horn', emoji: '🎺' },
  { id: 'tuba', name: 'Tuba', emoji: '🎺' },
  { id: 'recorder', name: 'Recorder', emoji: '🎼' },
  { id: 'harmonica', name: 'Harmonica', emoji: '🎵' },
  { id: 'xylophone', name: 'Xylophone', emoji: '🎼' },
  { id: 'glockenspiel', name: 'Glockenspiel', emoji: '🎼' },
  { id: 'marimba', name: 'Marimba', emoji: '🎼' },
  { id: 'vibraphone', name: 'Vibraphone', emoji: '🎼' },
  { id: 'bongo', name: 'Bongo Drums', emoji: '🥁' },
  { id: 'conga', name: 'Conga Drums', emoji: '🥁' },
  { id: 'djembe', name: 'Djembe', emoji: '🥁' },
  { id: 'tambourine', name: 'Tambourine', emoji: '🎵' },
  { id: 'triangle', name: 'Triangle', emoji: '🔔' },
  { id: 'cymbals', name: 'Cymbals', emoji: '🎵' },
  { id: 'gong', name: 'Gong', emoji: '🔔' },
];

// ---------- Vehicles (30+ emoji only) ----------
export const vehicles = [
  { id: 'car', name: 'Car', emoji: '🚗' },
  { id: 'bus', name: 'Bus', emoji: '🚌' },
  { id: 'train', name: 'Train', emoji: '🚂' },
  { id: 'airplane', name: 'Airplane', emoji: '✈️' },
  { id: 'boat', name: 'Boat', emoji: '⛵' },
  { id: 'bicycle', name: 'Bicycle', emoji: '🚲' },
  { id: 'truck', name: 'Truck', emoji: '🚚' },
  { id: 'firetruck', name: 'Fire Truck', emoji: '🚒' },
  { id: 'policecar', name: 'Police Car', emoji: '🚓' },
  { id: 'ambulance', name: 'Ambulance', emoji: '🚑' },
  { id: 'taxi', name: 'Taxi', emoji: '🚕' },
  { id: 'suv', name: 'SUV', emoji: '🚙' },
  { id: 'van', name: 'Van', emoji: '🚐' },
  { id: 'pickup', name: 'Pickup Truck', emoji: '🛻' },
  { id: 'tractor', name: 'Tractor', emoji: '🚜' },
  { id: 'motorcycle', name: 'Motorcycle', emoji: '🏍️' },
  { id: 'scooter', name: 'Scooter', emoji: '🛵' },
  { id: 'helicopter', name: 'Helicopter', emoji: '🚁' },
  { id: 'submarine', name: 'Submarine', emoji: '🛳️' },
  { id: 'cruise', name: 'Cruise Ship', emoji: '🚢' },
  { id: 'yacht', name: 'Yacht', emoji: '⛵' },
  { id: 'jetski', name: 'Jet Ski', emoji: '🚤' },
  { id: 'canoe', name: 'Canoe', emoji: '🛶' },
  { id: 'hotairballoon', name: 'Hot Air Balloon', emoji: '🎈' },
  { id: 'rocket', name: 'Rocket', emoji: '🚀' },
  { id: 'satellite', name: 'Satellite', emoji: '🛰️' },
  { id: 'ufo', name: 'UFO', emoji: '🛸' },
  { id: 'skateboard', name: 'Skateboard', emoji: '🛹' },
  { id: 'rollerskate', name: 'Roller Skate', emoji: '🛼' },
  { id: 'sled', name: 'Sled', emoji: '🛷' },
  { id: 'snowmobile', name: 'Snowmobile', emoji: '❄️' },
];

// ---------- Landmarks (20+ emoji only) ----------
export const landmarks = [
  { id: 'eiffel', name: 'Eiffel Tower', emoji: '🗼' },
  { id: 'pyramid', name: 'Pyramid', emoji: '🔺' },
  { id: 'statue', name: 'Statue of Liberty', emoji: '🗽' },
  { id: 'taj', name: 'Taj Mahal', emoji: '🕌' },
  { id: 'bigben', name: 'Big Ben', emoji: '⏰' },
  { id: 'colosseum', name: 'Colosseum', emoji: '🏛️' },
  { id: 'parthenon', name: 'Parthenon', emoji: '🏛️' },
  { id: 'machupicchu', name: 'Machu Picchu', emoji: '🏞️' },
  { id: 'christ', name: 'Christ the Redeemer', emoji: '🗿' },
  { id: 'sydney', name: 'Sydney Opera House', emoji: '🎭' },
  { id: 'petra', name: 'Petra', emoji: '🏜️' },
  { id: 'greatwall', name: 'Great Wall', emoji: '🧱' },
  { id: 'angkor', name: 'Angkor Wat', emoji: '🛕' },
  { id: 'burjkhalifa', name: 'Burj Khalifa', emoji: '🏢' },
  { id: 'leaningtower', name: 'Leaning Tower', emoji: '🗼' },
  { id: 'sphinx', name: 'Sphinx', emoji: '🦁' },
  { id: 'moai', name: 'Moai Statues', emoji: '🗿' },
  { id: 'kremlin', name: 'Moscow Kremlin', emoji: '🏰' },
  { id: 'stbasil', name: 'St. Basil Cathedral', emoji: '🕌' },
  { id: 'neuschwanstein', name: 'Neuschwanstein Castle', emoji: '🏰' },
  { id: 'alhambra', name: 'Alhambra', emoji: '🕌' },
];